server:
  port:9111
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jonmax_mybatis_plus?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: jonmax
    password: Kfcs@1234
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 15
      minimum-idle: 5

mybatis-plus:
  mapper-locations: classpath*:**/*Mapper.xml
  global-config:
    db-config:
      table-prefix: tb_
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
